### PR TITLE
Quotes + Tzeentch update

### PR DESCRIPTION
**Pull request by Zzwzzzz**
Quotes for guardsmen, commissar
Some more quotes for SoB
Rebalanced distances to hear quotes
Tzeentch quotes shows no source of sound
Tzeentch path is expanded and gained some fixes and improvements

### CODE REVIEW

**Comment by Zzwzzzz** [comment]
Screenshot_4

**Comment by Zzwzzzz** [comment]
Screenshot_5
In case if Github will say again that I changed map files

**Comment by ZAB909** [comment]
I'd say you should add the /obj/item/material/sword/demon to the list of craftables. I just added it back into the code, and its the most tzeentchy sword we have. Also make the strength to 14 cap at least. Theres a couple items you're just locking them out when it deducts strength.

**Comment by Zzwzzzz** [comment]
Demon sword will have own ritual, but strength 14? Tzeentch cultists rely on their abilities, but not big strength, but...I will do different ways of worship for that

**Comment by ZAB909** [comment]
There's a lotta shit that you need 14 just to play the game honestly. Just don't go higher than 14 and it's ok

**Pull request merged**
