### PR TITLE
Nurgle recipes fix & Daemons 

### PR DESCRIPTION
**Pull request by helloisitmeyourelookingfor**
-Blight Grenade back to being pipe bomb but now requires head and liver to craft
-Nurgling can now be summoned by offering an appendix 
-Summonable daemons are no longer hostile to cultists, sewer & dungeon daemons remain hostile to everyone

### CODE REVIEW

**Comment by TheVanderlin** [comment]
I really can't merge this unless you make the Rites actually cost something that isn't freely found from getting a corpse. Pipe bombs are one of the most common items in the game. You can get 5-10 of them easily as a Pilgrim without spending any thrones.

**Comment by TheVanderlin** [comment]
Also no compile screenshot.

**Comment by helloisitmeyourelookingfor** [comment]
There you go, Krak nade instead of ez pz pipe bomb. Updated tome too.

**Pull request merged**
