### PR TITLE
Literally just adds the new Marshal armor icons but doesnt actually change marshal armor icons yet

### PR DESCRIPTION
**Pull request by Teragenic**
image

Too lazy, will do tommorow, it's not a helmet and armor its one in both... So I have to do shit. Sooo not now.

### CODE REVIEW

**Comment by Teragenic** [comment]
Oh also the Icons are from

https://github.com/WoodenTucker/40K-Eipharius/pull/159

**Comment by Teragenic** [comment]
I just edited to make it a visor

**Comment by TheVanderlin** [comment]
Don't merge this. There's a conflict and Teragenic requested we hold off on a merge until he can fix the conflict(once they are home).

**Comment by TheVanderlin** [comment]
image

**Comment by WoodenTucker** [comment]
^

**Pull request closed without merging**
