### PR TITLE
Fixes a lot of shit

### PR DESCRIPTION
**Pull request by reklaw9**
**MOST IMPORTANTLY** -makes it so ghosts _CAN VOTE_ on votes.
-makes it so guardsmen,conscripts,sharpshooters have their roles on their names.
-removes "emperorrprotects" and adds the working theemperorprotects.
-fixes/balances cultist chances, medicae are more easy to go culty, specialists/sharpshootas are harder to go culty.
-buffs/nerfs/balances sergeant skills.
-gives Cadian Sergeant the "Tough" Quirk.
-Removes the "As the Commissar you answer to the RT and to the astartes, special circumstances may change this" and -Adds "As the commissar you listen to the RT and the Commissariat".
-Reworks the commissar "job starting text".
-Changes the file for heretical swords.
-Fixed Stunbatons(probably).
-Khornites can no longer abuse bioprinters to print out infinite hearts for infinite shit.
-Buffs StunProd slightly.
-Puts the "Chaos heart" thing on the END OF THE FILE NOT ON THE FUCKING START YOU FUCKING ANIMALS, DO NOT PUT SHIT INSIDE OF OTHER SHIT IF IT DOESNT INTERACT YOU LITTLE MOTHERFUCKERS I ALMOST FAILED--anyway.
-BioPrinted Eyes, WIP.
-Adds Heretek/Tzeentch Items, WIP for now. COULD BE USED FOR A EVENT!

### CODE REVIEW

**Comment by reklaw9** [comment]
image

**Comment by Zzwzzzz** [comment]
Is it right to keep bullet warning on?

**Comment by ZAB909** [comment]
Hey astra militarum having a warning is new, please fix that. Also ghosts voting disabled for a reason. So people just don't die enough, then vote restart. 

The commissar/guard are mercs, so they would answer to the astartes and not the commissariat

have you tested if the tzeentch laser cutter works? Also you should probably give them all 3 tools, as to craft anything, you must have 3 tools

Also if you could add the "Draw Rune" to a Ruinous Powers tab or some shit, instead of "IC" I would like it, but it isnt required

**Comment by reklaw9** [comment]
I will do it in the morning.

**Comment by reklaw9** [comment]
> Hey astra militarum having a warning is new, please fix that. Also ghosts voting disabled for a reason. So people just don't die enough, then vote restart. Ask Ravenor if its acceptable for them to vote, now.
astra... militarum warning??? 
dm'd ravenor about it, i will call you when im answered
> The commissar/guard are mercs, so they would answer to the astartes and not the commissariat
done.
> have you tested if the tzeentch laser cutter works? Also you should probably give them all 3 tools, as to craft anything, you must have 3 tools
its wip, but i will probably add it soon
> Also if you could add the "Draw Rune" to a Ruinous Powers tab or some shit, instead of "IC" I would like it, but it isnt required
done.

**Comment by reklaw9** [comment]
image

**Pull request merged**
