### PR TITLE
Nurgle abilities

### PR DESCRIPTION
**Pull request by CocaColaTastesGood**
1. Zombie: Makes the cultist more durable. No pulse, visibly decayed(Flavortext)
2. Heal: Lets nurgle cultists heal wounds, but they take toxin damage.

### CODE REVIEW

**Comment by TheVanderlin** [comment]
Lemme know when dis is ready.

**Comment by ZAB909** [comment]
Haven't read it cause I'm at work and unsure if it's already added. But something that tells the player that they're gonna have a KOS examine text now will be pretty important. So add that at the step they gain it ig

**Comment by CocaColaTastesGood** [comment]
> Haven't read it cause I'm at work and unsure if it's already added. But something that tells the player that they're gonna have a KOS examine text now will be pretty important. So add that at the step they gain it ig

sure

**Comment by CocaColaTastesGood** [comment]
image

**Comment by CocaColaTastesGood** [comment]
Thought process on balancing is that any visual changes should be OP. At that point you're pretty much a Daemon. Some way of making these changes visual would be very based.

**Comment by TheVanderlin** [comment]
Scot no idea if you've tested this on your build but supposedly Nurgle Path cannot be progressed. Should check it out.

**Comment by CocaColaTastesGood** [comment]
> Scot no idea if you've tested this on your build but supposedly Nurgle Path cannot be progressed. Should check it out.

All paths can progress except for Tzeentch. They just have no rewards.

**Comment by TheVanderlin** [comment]
Going to merge as I assume you want it. Next time just let me know though if you want it merged since I know you tend to modify your PR's after upload.

**Comment by CocaColaTastesGood** [comment]
> Going to merge as I assume you want it. Next time just let me know though if you want it merged since I know you tend to modify your PR's after upload. Your stuff doesn't need approval also, I just need to know when you want it merged. also boi respond to mah discord dm

I deleted my discord account.

**Pull request merged**
