### PR TITLE
Shitcodus Fixus 1, read please.

### PR DESCRIPTION
**Pull request by reklaw9**
gives medicae ALMOST the same stats as guardsman, they still have better stats tho. 
organizes guardsman+biologis shit.
gives enforcers the death tolerant trait.
gives arbites brave perk.
fixes skills and stats.
gives krieger grenadier a shovel.
gives some people lanterns.
makes arbitos speak high gothic
**fixes names and shit, now you have an actual reason to check who's a guard and who isn't, only person on guard with a forced name is commissar, enforcers also don't get their name changed, arbitos and marshal still have their title on name.**
buffs commissar melee a bit.
nerfs karskin str+melee a bit, we don't want them to be OP when we add them.
gives karskin the correct hotshot lasgun.
minor psyker changes, adds 2 spells, gives psyker 3 specials, sacrifice minor(new spell, heals target but damages healer), screech(new spell, screams loudly) and heal minor (heals 10-15 damage)
removes instakill succumb, ghost will help you leave this world now.
fixes putting mechadendrite shit into pockets
makes psyker screech spell use /carbon/ instead of /carbon/human, this is cause future coders may revamp nids.
fixes ghost, ghost has 3 options now: Cancel, Ghost, Admin Ghost, tested it, all 3 work perfectly on de-admined, players and admins.

image

### CODE REVIEW

**Comment by reklaw9** [comment]
image

**Comment by TheVanderlin** [comment]
I cannot merge stuff like this;

image


It's an established policy that Guardsman that aren't name worthy don't have their names replaced. The reason for this is it makes it impossible for people to join as PDF and also makes it so you can't disguise yourself as a Guardsman if you are a cultist or Inquisitor. Same for any other roles you added title prefixes to.

Titles sound cool but it changes your actual name, not your ID -- meaning no matter what you do. You can never hide the fact you are a Guardsman. This is fine for certain roles but not all.

**Comment by reklaw9** [comment]
> I cannot merge stuff like this;
> 
> image
> 
> It's an established policy that Guardsman that aren't name worthy don't have their names replaced. The reason for this is it makes it impossible for people to join as PDF and also makes it so you can't disguise yourself as a Guardsman if you are a cultist or Inquisitor. Same for any other roles you added title prefixes to.
> 
> Titles sound cool but it changes your actual name, not your ID -- meaning no matter what you do. You can never hide the fact you are a Guardsman. This is fine for certain roles but not all.

ITS BROKEN THO

**Comment by reklaw9** [comment]
THEY ONLY GET THEIR NORMAL NAME, NO ROLE SPECIFICATION.

**Comment by TheVanderlin** [comment]
image

**Comment by TheVanderlin** [comment]
BRO YOU CANNOT HAVE THE TITLE PREFIXES IN REPLACE CHARACTER NAME.

**Comment by TheVanderlin** [comment]
Nobody should be called Guardsman Joe Swanson

Or Sniper Joe Swanson

Your name is your name BOI

**Comment by reklaw9** [comment]
> Nobody should be called Guardsman Joe Swanson
> 
> Or Sniper Joe Swanson
> 
> Your name is your name BOI

everyone else has it.
i didnt add it, every guardsman role OTHER than krieger ones had it
but fine i will remove it from the guardsman ones (too lazy to do the rest)

**Comment by reklaw9** [comment]
its removed

**Comment by Xeltronix** [comment]
Good stuff

**Comment by reklaw9** [comment]
seems to work, didnt test psyker abilities tho, ready for merge i'd say.
image

**Pull request merged**
