### PR TITLE
RnD re-balance

### PR DESCRIPTION
**Pull request by BobNewman-max**
## About The Pull Request
Rebalances RnD for the admech

## Why It's Good For The Game

Stops them from being able to mass produce weaponry, changes the prices and removes plasma weaponry (they're commented out until further notice, not like they could produce them anyways.) 

Also added a debug item for deconstruction to give all of the major techs

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BobNewman-max** [comment]
Yes I know it has conflicts, I'm fixing them right now (it launches fine for me but github hates it.)

**Comment by BobNewman-max** [comment]
okay so apparently bolters don't like to be touched, I'll figure out why after this PR is merged, fuck bolters and fuck them refusing to have an increase in production costs. (it's probably me just doing dumb shit.

**Comment by TheVanderlin** [comment]
I can approve this once you revert the ammo changes. They're a bit too extreme for producing ammo.

That or make them less nerfed.

Also the Armor/Helmets requiring Combat 8 is really extreme.

It's just Flak/Carapace. Combat Level 8 is for you know, Bolters and Plasma.

**Comment by BobNewman-max** [comment]
another Commit, if the sort code is the cause to armors not being produced by the lathe I will actively shit myself in anger.

Also a note to rav, I won't change the nerfing/balancing of the ammo/armor due to the fact that I play the faction as pretty much the only active faction I play, I watch them reach this pretty much every round through trade/normal activities. The alternative would be to allow it to be 6/lower which is often done 10-20 mins into a round. 

With the nerf at 8, they'd get it at a norm of 30-40 mins into a round. Maybe 50-60 mins if you're unlucky and RT doesn't wake up. Though that's rare that not even a single Xeno Merc wakes up.

**Pull request merged**
