### PR TITLE
Planetary Investigator 

### PR DESCRIPTION
**Pull request by AndJusticeForAll0**
This adds a new role to the Magistratum. The Investigator is a role primarily focused on forensics and crime solving, as opposed to the more combat-heavy Enforcer. This also lowers the Enforcer slot by one to balance the addition of a new Magistratum role.

### CODE REVIEW

**Comment by ZAB909** [comment]
Make open when dead false.
Make the weapon skills at least 7. Code is funny rn and anything under 6 and you will not hit any shots
Change the outfit to be more similar to enforcer. You essentially just put base ss13 detective in it. It should look like its an enforcer still, but a detective one. But not a literal detective from ss13
Make sure to remove the pda and give it an ID that fits grimdark

**Comment by AndJusticeForAll0** [comment]
This was more or less an early draft, was going to fix it tomorrow

**Comment by WoodenTucker** [comment]
Why is this worth adding? This is like, 99% Inqusitor's entire purpose.

**Comment by AndJusticeForAll0** [comment]
I was told by Ravenor that this is the direction that Magistratum should go.

**Pull request closed without merging**
