### PR TITLE
Skulls for the Skulls Throne!

### PR DESCRIPTION
**Pull request by DrNukesky**
**What is this shit?**
Now you can butcher limbs of people to get cutlest. I'll add a recipe for corpse starch later if you merge this PR

**Skulls?**
Yeah, you can get skulls while butchering heads

**Why do we need skulls?**
Because i'm tired to see baby khornites getting salty about surgery method of removing hearts, moreover, skulls are more badass

**Is those skulls are good for something else?**
Currently - no. Feel free to code it. They can be good to make servoskulls, decorations, armor, etc. You can add sale_price if you want to make them sellable. Or say its price to me and i'll add it.

**Does it compiles?**
Capture

**Does it works properly?**
At least nothing was broken
https://youtu.be/g5s2HB5ioTg

### CODE REVIEW

**Comment by DrNukesky** [comment]
**What is this shit?**
Now you can butcher limbs of people to get cutlest. I'll add a recipe for corpse starch later if you merge this PR

**Skulls?**
Yeah, you can get skulls while butchering heads

**Why do we need skulls?**
Because i'm tired to see baby khornites getting salty about surgery method of removing hearts, moreover, skulls are more badass

**Is those skulls are good for something else?**
Currently - no. Feel free to code it. They can be good to make servoskulls, decorations, armor, etc. You can add sale_price if you want to make them sellable. Or say its price to me and i'll add it.

**Does it compiles?**
Capture

**Does it works properly?**

**Comment by Zzwzzzz** [comment]
A little conflict moment. And...did you just made Khorne path only with skulls? Skulls for the skull throne and skull for the blood god? Also that's a little weird coding where you get two benefits for one skull with no even heart. Can I just...use your skull sprite and code to make it properly?

**Comment by DrNukesky** [comment]
> A little conflict moment. And...did you just made Khorne path only with skulls? Skulls for the skull throne and skull for the blood god? Also that's a little weird coding where you get two benefits for one skull with no even heart. Can I just...use your skull sprite and code to make it properly?

sure, use it

**Comment by DrNukesky** [comment]
> A little conflict moment. And...did you just made Khorne path only with skulls? Skulls for the skull throne and skull for the blood god? Also that's a little weird coding where you get two benefits for one skull with no even heart. Can I just...use your skull sprite and code to make it properly?

how is it goning? Any luck?

**Comment by DrNukesky** [comment]
Closed because there is still no proper cult system

**Pull request closed without merging**
