### PR TITLE
Access to exosuit fabricator

### PR DESCRIPTION
**Pull request by DrNukesky**
RT and his crew have a exosuit fabricator in their lab, but no access to it. This PR fixing this

### CODE REVIEW

**Comment by Rakunoshin** [comment]
it should be removed instead

**Comment by TheVanderlin** [comment]
i cant merge mapping since feral is doing a gigantic map update rn -- just dm feral the issue

**Comment by DrNukesky** [comment]
Its not a mapping, its constant requirement for any exosuit fabricators. Binded to access cards

**Comment by oprimeolt** [comment]
It should be removed tbh not added

**Pull request merged**
