### PR TITLE
modern TGUI, TGChat, Statusbar

### PR DESCRIPTION
**Pull request by CocaColaTastesGood**

### CODE REVIEW

**Comment by CocaColaTastesGood** [comment]
image

**Comment by CocaColaTastesGood** [comment]
ready

**Comment by CocaColaTastesGood** [comment]
note that compiling would have to be done using build.bat in tools instead of normally otherwise TGUI wouldn't recompile

**Comment by TheVanderlin** [comment]
There's some conflicts with the borer code. oy vey

**Comment by CocaColaTastesGood** [comment]
> we hate TGUI

There already is TGUI + only NPCs say this

**Comment by TheVanderlin** [comment]
image

image


Can you give context to this? It's from your PR.

**Comment by CocaColaTastesGood** [comment]
forgot to implement hands_can_use_topic 
was reverted anyways so no point in bothering.

**Comment by Magisterium2022** [comment]
Dammit, this overwrote half of my changes. Next time, check you're up-to-date before merging.

**Pull request merged**
