### PR TITLE
Added ability to change name on otherwise random or unfitting roles.

### PR DESCRIPTION
**Pull request by MagmaSlasher**
Added the ability to change the automatic name for the following roles from the player setup menu.

- Ogryn
- Adepta Sororitas (This allows players to have SoB jobs enabled while still using an otherwise male preset.)
- Adeptus Astartes (Same as SoB, but the other way around.)
- Orks
- Kroot
- T'au

listofnames

The system put in place makes it easy to add customizable names for other roles through the code. It also adds the ability to randomize these names from the menu.
Sororita and Astartes names will be sanitized like normal names, and will default to the name of the preset if the character's gender corresponds.
This is untested with existing save files, but there's no reason why it wouldn't work as normal.

proofofcompile

### CODE REVIEW

**Comment by TheVanderlin** [comment]
Before this can be merged need to fix the Progena.

Progena are not only female, you have some code in there that forces them to get a random name if male.

**Comment by MagmaSlasher** [comment]
@TheVanderlin Where is the datum for the Progena role? I tried searching the repo for "Progena" and only found some code relating to the spawnpoint. If I understand correctly, and they're a Ministorum role, then all three of the roles in that file that have the alternate names enabled already had `H.gender = FEMALE` in their equip proc.

**Comment by MagmaSlasher** [comment]
Turns out I was using an outdated fork. Should still work though, I changed the relevant files to be accurate. Github is still showing conflicts, but I don't think there's any actual issue with it.

**Comment by reklaw9** [comment]
you forgot to remove the 3 lines that force progena to be bald + female

**Comment by TheVanderlin** [comment]
You gotta remove the forced female / bald thing. The novitae.

Your fork is working off an Ecclesiarchy that no longer exists it needs to be updated to follow current dude.

**Comment by MagmaSlasher** [comment]
Yeah I noticed it was outdated. Didn’t realize that was the case until I was already well into working on it. My bad.

**Comment by MagmaSlasher** [comment]
Forgot to include this as well. Should be good now, no conflicts, it works as intended, and it compiles.
image

**Comment by TheVanderlin** [comment]
thanks papi

**Pull request merged**
