### PR TITLE
Role Bloat Check

### PR DESCRIPTION
**Pull request by BobNewman-max**
## About The Pull Request

Literally just straight up removes a load of roles to see how the players interact with the change

## Why It's Good For The Game

If this goes well, the roles removed will be merged (when I get around to it) with other roles to allow for less role bloat. More slots have been opened to make it fair. Should allow for a cleaner looking occupations sheet, the less role options there are and the more grouped together roles are the better the environment for lower pop-hosts can be. Also, there are players who've joined that I've seen who have 0 clue which role to pick and end up just grabbing one because they don't know which to choose (to be fair, only had 2 cases of this) so I'd see the lower number of roles possibly helping this. The loadouts/armors/guns wont be removed if they get merged, just changed to a loadout of the role it gets merged with. 

MAKE SURE NOT TO BE A GLUE EATER AND MERGE THIS.

Test merge it to see the response of the playerbase, don't just throw it in and forget to pull it out. ITS ONLY TO GAIN INFO ON THE PLAYERS THOUGHTS NOT TO FULLY MAKE A CHANGE YET

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Teragenic** [comment]
Role bloat -> Literally removes the entire cargo faction.

Triples the size of the Guard.

No.

**Comment by BobNewman-max** [comment]
> Role bloat -> Literally removes the entire cargo faction.
> 
> Triples the size of the Guard.
> 
> No.

The guard being increased allows for those who are new to join up easily, removes RT because the role as itself could easily be changed as to fit the planet better, such as house sondar being the main logi group rather then RT, because so far what does the RT do other then spawn with gear and occasionally sell guns to pilgrims and buy from them, what is UNIQUE that an RT can do that house sondar couldnt if they were given logi gear and the ability to trade?

As for the guard increase, I'll admit, the guards increase was over the top but I want to see just from 1 round how that interacts with server flow. Not for an actual longterm change but just to see how it effects the round.

**Comment by BobNewman-max** [comment]
RT Re-added, it'll be tested again in future if able

**Comment by TheVanderlin** [comment]
Uh this isn't really a pull request. It's basically just a request or a suggestion. Any dev on the game could do this in like 5 seconds themselves if they wanted to.

I will keep in mind the suggestion of the Rogue Trader owning perhaps the Sondar Mansion and combining the factions into one. Perhaps a pact of some kind of the RT as the  head of the house, with their heirs. 

Doing that, mapping and coding those changes + role descriptions is a pull request.

This is changed a few numbers. We're trying to do better then that.

**Comment by TheVanderlin** [comment]
Also I'm currently busy fixing the brand new 773 file-change map update from Feral and introducing new mapping changes.

We're also a heartbeat away from psykers, genestealer cults and a lot of new art content. So I'll get to htis when I have time.

**Pull request closed without merging**
