### PR TITLE
added armor and uniform recipes to nurgle rune

### PR DESCRIPTION
**Pull request by helloisitmeyourelookingfor**
Simplified some of the recipes, Nurgle cultists can now make uniforms,armor and masks for the day of rope!

### CODE REVIEW

**Comment by ZAB909** [comment]
Make it so it's just 1 cloth 
You can remove the head requirement from the ngana, they're gonna kill people anyway
Revert the symbol desc changes, they are made from people's blood after all. It is a little weird making a bright purple icon from blood but whatever.

**Comment by helloisitmeyourelookingfor** [comment]
>It is a little weird making a bright purple icon from blood but whatever.

It doesn't make sense indeed, so why leave it that way? There's no reason for it to not make sense

**Comment by ZAB909** [comment]
Because the verb for actually creating a rune tells the player that they are drawing it with their blood

**Comment by helloisitmeyourelookingfor** [comment]
No, look 

`/mob/living/carbon/human/proc/draw_rune()
	set category = "Ruinous Powers"
	set name = "Draw Rune"
	if(isdrawing == 0)
		isdrawing = 1
		visible_message("[src] starts drawing a strange shape on the floor.")`
		
See? no mention of blood at all

**Pull request merged**
