### PR TITLE
Ganger Expansion/Rework

### PR DESCRIPTION
**Pull request by AndJusticeForAll0**
This update reworks the ganger faction by introducing two main things. First, they now have three archetypes similar to the pilgrim, Bruiser, Hitman, and Rogue Doc. Sociopath was cut out due to not really having a place. They also have a leader, the Underboss who has replaced the Innkeeper and is now in charge of both the gangers and the Inn. The ganger base has been relocated to be next to the inn as well.
Forgive me if this fucking sucks, I did most of the code at 2 am in the morning.

### CODE REVIEW

**Comment by AndJusticeForAll0** [comment]
[
Screenshot 2023-02-20 124606
](url)

**Comment by TheVanderlin** [comment]
as lord mapper i must witness the mapping changes to approve

**Comment by TheVanderlin** [comment]
also give the innkeep his apron back. its the most iconic thing about them

**Comment by TheVanderlin** [comment]
Also lastly if the Gangers now technically number 6 Slots, including the Bouncer + Underboss.

Their total slots need to be reduced by 1 at least. Especially if we add a Gang Boss later.

**Pull request merged**
