### PR TITLE
modern TGUI/Statusbar/Examine blocks

### PR DESCRIPTION
**Pull request by CocaColaTastesGood**
stole a bunch of code from f19 for a project I'm doing, don't complain about conflicts this is a draft

### CODE REVIEW

**Comment by CocaColaTastesGood** [comment]
image

**Comment by CocaColaTastesGood** [comment]
image

**Comment by CocaColaTastesGood** [comment]
Not showing off examine blocks for now because they are ugly

**Comment by CocaColaTastesGood** [comment]
Bugs have been fixed, just need to switch verbs over to addverb so the statpanel properly updates

**Comment by TheVanderlin** [comment]
?

**Comment by TheVanderlin** [comment]
Also Cola if you want to keep contributing I need some way of contacting you brother.

My discord; Vanderlin#2800 if you make a new account.

**Pull request closed without merging**
