### PR TITLE
Cult refactor part 1

### PR DESCRIPTION
**Pull request by CocaColaTastesGood**
An attempt to completely change how cults work and improve on their code.

### CODE REVIEW

**Comment by CocaColaTastesGood** [comment]
not ready for merge

**Comment by CocaColaTastesGood** [comment]
Don't have the time to finish this. It's nearly in a ready state though honestly.

**Comment by Daelso** [comment]
This honestly looks a million times better even if it more "complex" than our last one. What exactly remains to be done?

**Comment by CocaColaTastesGood** [comment]
> This honestly looks a million times better even if it more "complex" than our last one. What exactly remains to be done?

Recipes weren't ported over completely, tzeentch is kind of lackluster, masochism ability might not work, and favor is kind of useless. It should compile though.

**Comment by CocaColaTastesGood** [comment]
I'm going to do a quick check.

**Comment by Daelso** [comment]
If you can leave me with a list of what needs fixing its probably fine as is. This is a far better base to build off of then our previous.

**Comment by CocaColaTastesGood** [comment]
Alongside what I said above, Nganga also appears to not work. I'll just re-add the old one for now, not quite sure what's causing it to mess up.

**Comment by CocaColaTastesGood** [comment]
Nganga appears to work now, and masochist was removed. Just the above mentioned issues exist.

**Comment by TheVanderlin** [comment]
Just let us know when it's ready. Oh also Wooden if Coca says it's gucci then just merge.

**Comment by CocaColaTastesGood** [comment]
It should be good for merge. Compiles on my end.

**Comment by TheVanderlin** [comment]
> It should be good for merge. Compiles on my end.

always post the screenshot though. its de policy now

**Comment by CocaColaTastesGood** [comment]
github messed something up actually

**Comment by CocaColaTastesGood** [comment]
image

**Pull request merged**
