### PR TITLE
BALANCING: read description

### PR DESCRIPTION
**Pull request by reklaw9**
Balances omnissian axe, gives it pen among other things.
Gives galvanic rifle a better desc, makes their bullets give EMP, gives it a AIM ability.
balances ogrino shit.
makes ecclesiarchy confessor and priest a bit more accurate to lore, confessor is a chad, priest is a nerdboy.
Nerfs shit-ster stats and skills, they aren't supposed to be the same as astartes in any way, as strong as they may be, over 20 is only for intelligence, endurance or modded people.
Nerfs Novice sister stats, while technically they JUST started training and never went to battle, they have now stats that are comparable to a guardsman cadet.
Balances phosphor blast pistol properly, its not TOO OP anymore.
nerfs power claw block chance.
image

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
You should substantially reduce the parry chance on this thing a fair bit if you're gonna give it assloads of AP, especially since it seemingly has very high attack speed. 

Also your comment is still wrong, drusian is 50 AP not 75 :)

**Comment by reklaw9** [comment]
> You should substantially reduce the parry chance on this thing a fair bit if you're gonna give it assloads of AP, and make it attack slower too since from what I can tell it attacks at the speed of a knife.
> 
> Also your comment is still wrong, drusian is 50 AP not 75 :)

Skill issue, fixed.

**Comment by Magisterium2022** [comment]
Galvanic rifles, while they have EMP in the lore, probably shouldn’t in-game, since it’s got a somewhat wonky effect on a lot of stuff.

**Comment by reklaw9** [comment]
considering that ranger currently is the WEAKEST skitarii, he really needs the ability to take down certain specific enemies (dreadnoughts and shit) so that theres an real reason to go ranger, atm all he has is a shitty galvanic rifle compared to the other skitarii units

**Comment by Magisterium2022** [comment]
Oh, I agree that Rangers need some balancing, but within the theme. The galvanic rifle should be able to load multiple different types of ammo, hit me up if you need them added.

**Comment by Magisterium2022** [comment]
They should theoretically function as a multiple-role, adaptable unit.

**Comment by reklaw9** [comment]
you are right, but atm EMP bullets should make them a little more spicy.

**Comment by Sparrowbird611** [comment]
Ranger will always suck unless he has some innate ability, cause you can just give a vanguard a galvanic.

Also why did you buff ogryn ranged skill, I thought ogryn were supposed to have dogshit ranged to emphasize their melee roles.

**Comment by reklaw9** [comment]
> Ranger will always suck unless he has some innate ability, cause you can just give a vanguard a galvanic.
> 
> Also why did you buff ogryn ranged skill, I thought ogryn were supposed to have dogshit ranged to emphasize their melee roles. Shouldn't it be going down to skitarii ruststalker tier.

you wrong about the vanguard with galvanic right thing, however, making the ranger spawn with a good weapon is a step in the right direction, as much as its not the best thing, in later commits i plan to MAYBE make it so you cant normally craft the galvanic rifle, but im not about to risk this specific PR by adding such a controversial change as doing that(YES ITS CONTROVERSIAL FUCK U!!!!).

bullgryn is better than normal ogrynos at ranged

**Comment by Magisterium2022** [comment]
The Vanguard still needs to have their slowdown fixed, they should be moving much more slowly. Other than that, I’ll work on some new ammo types, and the use of an active ability could be good. Or making them separate sub-species, with the robotic limbs as an optional thing. That way you can customise them, with Ruststalkers having weak but fast limbs, Rangers in the middle, and Vanguards being slow but durable.

**Review by ZAB909 — APPROVED** [review]

**Pull request merged**
