### PR TITLE
Light Power Armor, if you rich enough

### PR DESCRIPTION
**Pull request by DrNukesky**
**What is This?**
Power armor, light version, made for common humans. Malleus inquisitor and SoB's have almost same.

**Lore friendly?**
Totally. You can find it in Dark Heresy rulebook, page 145 (https://christophedia.com/Repository/DarkHeresy/Dark%20Heresy%201st%20Edition/Whitespace%20Dark%20Heresy%2040k.pdf)

**How to get it?**
450 thrones at trade console

**Why 450?**
In sake of server balance. Its providing fair more protection than carapace

**Why is it good for game?**
Motivates people to make money, not just freeze their asses in the trenches while waiting for a late party

### CODE REVIEW

**Comment by ZAB909** [comment]
Um, no. We're not basing our balance on a book games workshop made from 2008 for a tabletop game. We use common sense, sure. Like how an ork is kinda meant to be stronger than a guardsmen, and have innaccurate weapons, because that's what an ork generally is. Not fancy or accurate, but strong and has enough stupidpower to brute force things. Plus games workshops' numbers are always unbalanced in their game

A primaris is 20 points I think for a basic bitch currently on tabletop. a scion is either 9 or 11, i can't find superb info. Anyway. Does that mean 2 scions should be as powerful as our space marine on Eipharius? No. 

It's quite easy to get thrones if you know what you're doing. The church has over 400 thrones and if the deacon wants to arm 3 sisters with this, they can quite easily. Including the SOB, they'd have 4 PA...The inquisition could do something similar if they wish, the current noble estate isn't used a whole tonne, but its useful enough for specialist things, but a very good armor much be exceedingly expensive. I'd say almost double it outright. The second best obtainable chainsword in the game is 90 thrones at the shop, and the shop is being reworked entirely to be like roguetowns'. I'd say make the helmet 250, and the suit also 250.

**Comment by DrNukesky** [comment]
> Um, no. We're not basing our balance on a book games workshop made from 2008 for a tabletop game. We use common sense, sure. Like how an ork is kinda meant to be stronger than a guardsmen, and have innaccurate weapons, because that's what an ork generally is. Not fancy or accurate, but strong and has enough stupidpower to brute force things. Plus games workshops' numbers are always unbalanced in their game
> 
> A primaris is 20 points I think for a basic bitch currently on tabletop. a scion is either 9 or 11, i can't find superb info. Anyway. Does that mean 2 scions should be as powerful as our space marine on Eipharius? No.
> 
> It's quite easy to get thrones if you know what you're doing. The church has over 400 thrones and if the deacon wants to arm 3 sisters with this, they can quite easily. Including the SOB, they'd have 4 PA...The inquisition could do something similar if they wish, the current noble estate isn't used a whole tonne, but its useful enough for specialist things, but a very good armor much be exceedingly expensive. I'd say almost double it outright. The second best obtainable chainsword in the game is 90 thrones at the shop, and the shop is being reworked entirely to be like roguetowns'. I'd say make the helmet 250, and the suit also 250.

So, should we just rise up price of this armor to 500 (suit+helmet) or its just impossible for nobles to order it via trading console? It's okay if the armor idea is rejected. I just want to be able to order something really expensive and worthwhile in the trading console

**Comment by Teragenic** [comment]
Just another thing... Can you make a red/blue texture for Marshal? :3

**Comment by ZAB909** [comment]
> So, should we just rise up price of this armor to 500 (suit+helmet) or its just impossible for nobles to order it via trading console? It's okay if the armor idea is rejected. I just want to be able to order something really expensive and worthwhile in the trading console

There is literally an entire role of power armor for humans. And there's 3 sets of PA already in the church. I'd say 225 is the absolute minimum we can have a helmet or armor  for, so 450 total. Eipharius is a backwater shit hole, and someone is reworking the entire economy. I'd rather have this be too expensive than too cheap before then. It will get readjusted like everything else. 

Also the helmet desc says its out of plasteel, but the armor isn't. Might want to update it

**Comment by DrNukesky** [comment]
> 

then I think that it would be more logical to wait for the economy to be reworked, and then return to this PR.

**Comment by ZAB909** [comment]
Its gonna be weeks upon weeks. Just make the cost 225 per piece and commit, its ok

**Comment by DrNukesky** [comment]
> Its gonna be weeks upon weeks. Just make the cost 225 per piece and commit, its ok

Done!
Its 450 for whole set, because the PA helmet is part of the exoskeleton itself and cannot be worn separately like PA hood of Malleus Inquisitor . Worth doing the same for Astartes PA someday

**Comment by Doosteroni** [comment]
> Um, no. We're not basing our balance on a book games workshop made from 2008 for a tabletop game. We use common sense, sure. Like how an ork is kinda meant to be stronger than a guardsmen, and have innaccurate weapons, because that's what an ork generally is. Not fancy or accurate, but strong and has enough stupidpower to brute force things. Plus games workshops' numbers are always unbalanced in their game

Lmao boohoo dog get some bitches you sound like fucking soy talking like that kek

**Comment by ZAB909** [comment]
go back to 4 chan please

**Comment by TheVanderlin** [comment]
Sorry we gotta close this PR. You'll need to add your PA to the new cargo system. Which is located in the Cargo Folder.

It's actually solid and I agree with it, just you added the armor to a file we deleted last night kek.

**Pull request closed without merging**
