### PR TITLE
Mapping, Icons + Virus

### PR DESCRIPTION
**Pull request by TheVanderlin**
Updated the map;

Moved the farm to south of chapel and created a mini-village around it.

Virology is now attached to the clinic in the city and the clinic has been expanded.

Added loot / edited the map quite a bit and generally tried to make some neglected roles more rewarding with spawn gear.

Reliquery is snazzy.

Updated items;
Added a whole bunch of helmet, armor items + 1 new cloak. Also updated cargo.

Updated nurgle virus to not make you shit your pants every 5 seconds and also not spread the plague using a verb. It's substantially more tame now and 4 times less contagious. 

Fixed machete icon.
Fixed omnissiah axe being sellable.

Updated Regen;
Regen nerfed slightly especially for assfartes/orks since they already OP motherfuckers. They shouldn't regen brain damage / toxin honestly. If you get brain damage as an astartes it means someone fucked you up, so you aren't getting back up. Timer to regen blood also increased, since losing blood as an Astartes shouldn't be something that doesn't mess up your day.

image

### CODE REVIEW

**Comment by TheVanderlin** [comment]
wow you are so sexy man never have i met you in my life i love your pull request. i will approve right now.

thank u for hard work.

**Comment by TheVanderlin** [comment]
> wow you are so sexy man never have i met you in my life i love your pull request. i will approve right now.
> 
> thank u for hard work.

uwu senpai i live to serve

**Comment by DrNukesky** [comment]
Do we also have schizophrenia virus? OwO

**Comment by TheVanderlin** [comment]
I'll be adding a lot more viruses later on.

I also want to expand the map a lot and make it so fucking sexy that people forget it was ever made by my dumbass.

**Comment by DrNukesky** [comment]
Also finally some fucking good PA, i love it <3

**Pull request merged**
