### PR TITLE
Removes pixel aiming

### PR DESCRIPTION
**Pull request by CocaColaTastesGood**
Didn't seem like any extra calculations are needed. Projectiles paths are changed depending on skill. So if you're good at shooting, you always shoot straight. If your aim is shit you shoot more wildly. At least that's how it should work.

### CODE REVIEW

**Comment by TheVanderlin** [comment]
We should do a weapon skill pass on every role at some point. Perhaps you? I'm not sure how skills will effect the update, but they are for SURE not balanced in any way. Skills are just... random and hard to understand. We have no rule system for it or baseline.

**Comment by CocaColaTastesGood** [comment]
I tested this with guardsmen. The base hit chance is rather poor with shitty skills, but I believe bearable. I'm hoping that I could get some feedback on a playtest to better fine tune it.

**Comment by TheVanderlin** [comment]
> I tested this with guardsmen. The base hit chance is rather poor with shitty skills, but I believe bearable. I'm hoping that I could get some feedback on a playtest to better fine tune it.

I'd be interested in you doing the pass anyway though. I think you'll do a better job then me at figuring out what skills we want to have.

You want to have a difference between different skill levels, but never make people feel like they are completely useless.

A pilgrim is never going to match up to a Guard, but they shouldn't be whacky inflatable arms when trying to do melee or miss all their shots. It's more that, you want people who play Guard to feel stronger then a Pilgrim. But at the same time avoid having Pilgrims feel like they're just stupidly weak. There's a nice balance we can find.

Same applies to Astartes, Scion - etc. Those roles should notice like "god damn I'm fucking good at killing people."

**Comment by CocaColaTastesGood** [comment]
> > I tested this with guardsmen. The base hit chance is rather poor with shitty skills, but I believe bearable. I'm hoping that I could get some feedback on a playtest to better fine tune it.
> 
> I'd be interested in you doing the pass anyway though. I think you'll do a better job then me at figuring out what skills we want to have.
> 
> You want to have a difference between different skill levels, but never make people feel like they are completely useless.
> 
> A pilgrim is never going to match up to a Guard, but they shouldn't be whacky inflatable arms when trying to do melee or miss all their shots. It's more that, you want people who play Guard to feel stronger then a Pilgrim. But at the same time avoid having Pilgrims feel like they're just stupidly weak. There's a nice balance we can find.
> 
> Same applies to Astartes, Scion - etc. Those roles should notice like "god damn I'm fucking good at killing people.". Right now the only thing that makes those roles strong is their gear or having a high strength score.
> 
> ALSO lastly.
> 
> One hundred percent sure that skills right now are not at all lined up properly. I just read some code that had the Commissar less skilled and weaker then Guardsmen.

I honestly have no idea what the values should look like. From what I see Commisars are quite stronger and better skilled than guardsmen. I'm going to raise the average skills a little bit, and some other tweaking for military roles.

**Pull request merged**
